name: drlnd-colab-compet
channels:
  - defaults
dependencies:
  - python=3.6
  - pip
  - pip:
     - torch==1.7.1
     - gym==0.10.5
     - jupyter
     - jupyterlab
     - matplotlib
     - seaborn
     - tensorboardX
     - unityagents==0.4.0
     - protobuf
    #  - mlagents==0.9.0
     - tqdm