name: drlnd-crawler
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.6
  - pip
  - pytorch=1.7.1
  - cudatoolkit=11.0.221
  - tensorboardX
  - pip:
     - jupyter
     - jupyterlab
     - matplotlib
     - seaborn
     - mlagents==0.27.0
     - mlagents-envs==0.27.0
     - tqdm